### ISSUE TITLE
How to build the linux debian package?

### ISSUE THREAD

**Issue by macauleycheng** [open-switch/opx-onie-installer#10]
When creating the NOS, it will go to Dell to get Linux kernel Debian package.
How to build this Linux kernel Debian package.
I need to put a patch to support our HW platform?
I use the same config file, but I still can't have the same behavior of Dell Linux kernel Debian packet.
Dell kernel Debian package have dependency on initramfs-tool.

**Comment by jeffyin-dell** [comment]
Your HW platform needs to be defined via XML files in opx-platform-config. There are several examples in there to follow, but please reach out to us for further support, either via GitHub or chat.openswitch.net

OPX does not make modifications to the Linux kernel.

For now, I'll close this issue since it hasn't been updated in a while.
